### Post user register
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "email": "someusername@gmail.com",
  "password": "q1w2e3",
  "username": "someusername",
  "avatar": "https://shorturl.at/blHPW",
  "isPremium": false,
  "isEmailApproved": false
}

### Post user login (email)
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "someusername@gmail.com",
  "password": "q1w2e3"
}

### Post user login (username)
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "username": "someusername",
  "password": "q1w2e3"
}
